In [5]:
import numpy as np

In [5]:
my_list=[10,20,30,40]


In [7]:
type(my_list)

list

In [9]:
np.array(my_list)

array([10, 20, 30, 40])

In [15]:
my_numpy_array=np.array(my_list)


In [17]:
type(my_numpy_array)

numpy.ndarray

In [19]:
 np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.random.random(5)

array([0.13655191, 0.52637026, 0.34045837, 0.07598768, 0.12287674])

In [23]:
#array arıthmetic

In [25]:
mylist1=[1,2]

In [27]:
mylist2=[2,3]

In [29]:
mylist1+mylist2

[1, 2, 2, 3]

In [31]:
numpyarray1=np.array(mylist1)

In [33]:
numpyarray2=np.array(mylist2)

In [35]:
numpyarray1+numpyarray2

array([3, 5])

In [37]:
numpyarray1*numpyarray2

array([2, 6])

In [39]:
numpyarray1*10

array([10, 20])

In [41]:
mylist1*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [45]:
np.arange(0,20,2) #range fonk gibi işte

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np_array=np.arange(0,10)

In [49]:

np_array[1]

1

In [51]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
#random

In [55]:
np.random.randn(4)

array([-0.21732694, -0.13424503, -0.97477606, -2.09851197])

In [11]:
first_matrix=np.array([[10,20,30]])

In [13]:
first_matrix.shape

(1, 3)

In [15]:
secon_matrix=np.array([[2,3],[2,3],[2,3]])

In [17]:
secon_matrix.shape

(3, 2)

In [21]:
resultmatrix=first_matrix.dot(secon_matrix)

In [23]:
resultmatrix.shape

(1, 2)

In [25]:
print(resultmatrix)

[[120 180]]


In [27]:
new_array=np.random.randint(1,100,20)

In [31]:
new_array

array([ 9, 48, 52, 76, 36, 10, 94, 56, 54, 28, 77, 59, 44, 44, 14, 72, 29,
       93, 21, 78])

In [33]:
new_array>25

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [35]:
new_array[new_array>25]

array([48, 52, 76, 36, 94, 56, 54, 28, 77, 59, 44, 44, 72, 29, 93, 78])

In [37]:
new_array[new_array<25]

array([ 9, 10, 14, 21])

In [39]:
data =np.array([10,12,13,15,18,25,100,105])

In [41]:
mean=np.mean(data)

In [43]:
mean

37.25

In [45]:
std=np.std(data)

In [47]:
std

37.9333296719389

In [49]:
z_scores=(data-mean)/std

In [51]:
z_scores #outlier olan verilerin z score yuksek çıktı 

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [55]:
z_scores[z_scores>1]

array([1.65421809, 1.78602829])